// VisualProfilerBackend.idl : IDL source for VisualProfilerBackend
//

// This file will be processed by the MIDL tool to
// produce the type library (VisualProfilerBackend.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
// GUID = DOB-Random-Version-type(1-interface, C-class, B-Library)-interface(0-neutral, 1-sampling, 2-tracing )
[
	object,
	uuid(19840906-C001-0000-0001-000000000001),
	pointer_default(unique)
]
interface ISamplingProfiler : IUnknown{
};
[
	object,
	uuid(19840906-C001-0000-0001-000000000002),
	pointer_default(unique)
]
interface ITracingProfiler : IUnknown{
};
[
	uuid(19840906-C001-0000-000B-000000000000),
	version(1.0),
]
library VisualProfilerBackendLib
{
	importlib("stdole2.tlb");
	[
		uuid(19840906-C001-0000-000C-000000000001)		
	]
	coclass SamplingProfiler
	{
		[default] interface ISamplingProfiler;
	};
	[
		uuid(19840906-C001-0000-000C-000000000002)		
	]
	coclass TracingProfiler
	{
		[default] interface ITracingProfiler;
	};
};

